DROP TABLE IF EXISTS cards CASCADE;
DROP TABLE IF EXISTS players CASCADE;

CREATE TABLE cards (
    id SERIAL PRIMARY KEY NOT NULL,
    content varchar(360),
    is_black_card boolean
);

CREATE TABLE players (
    id SERIAL PRIMARY KEY NOT NULL,
    username varchar(25) NOT NULL,
    play_card INT REFERENCES cards(id)
);

INSERT INTO cards(content, is_black_card)
    VALUES('test white card', false),
           ('Times have changed, girlfriend. If you want to meet people in New York, you got to be down for _____', true),
           ('Its beginning to look a lot like _____', true),
           ('Whats the one thing that makes an elf instantly ejaculate?', true),
           ('Its finally happening! Im finally doing it! Yes! Its time for _____'),
           ('Say it loud! Im _____ and Im proud'),
           ('Rub a dub dub, _____ in a tub!'),
           ('Aint it nifty? Bard and Bob hit 50! So get off your ass and raise a glass to 50 years of _____', true),
           ('I have solved politics. My solution is _____', true),
           ('You city folk would never understand the quiet dignity of _____', true),
           ('Comedy = Tragedy + _____.', true),
           ('Alright everybody, HOLD! Kelly, why is ther _____ on my stage', true),
           ('This season at Manhattan Theatre Club: "Whos afraid of _____?"', true),
           ('Match-maker, match-maker, make me a match. Find me _____', true)
           ('Im just gonna stay in tonight. You know, Netflix and _____', true),
           ('TRIGGER WARNING: _____', true),
           ('What did I nickname my genitals', true),
           ('Dont worry, Penny! Go Go Gadget _____!', true),
            ('This app is basically Tinder, but for _____.', true),
            ('Nothing says "I love you" like _____', true),
            ('You guys, you can buy _____ on the dark web.', true),
            ('A hamburger on a string that keeps getting pulled away.', false),
            ('A hateful 30-year marriage.', false),
            ('How quiet the forest is', false),
            ('A magician fucking up over and over again.' false),
            ('Letting this loser eat me out.', false),
            ('A vagina that beatboxes when its horny', false),
            ('a bold red lip.', false),
            ('This boring-ass white bitch from work.', false),
            ('An 800-foot-long pool noodle.', false),
            ('How many bagels I can fit on my penis.', false),
            ('The awesome power of the Lord.', false),
            ('Owing a lot of money to some very bad people.', false),
            ('Violating the geneva convention', false),
            ('Assembling IKEA furniture.', false),
            ('Mark Zuckerberg', false),
            ('Voldemort', false),
            ('Carlos Santanas horrible wailing guitar', false),
            ('An elite squad known as the Special Victims Unit.', false),
            ('Foul vegan shits.', false),
            ('Blue Smoke coming out of my anus.', false),
            ('My sons dipshit friends', false),
            ('These breasts of mine.', false),
            ('The little-known fact that Polish people dont dream.', false),
            ('All my dead sisters.', false),
            ('Clearly asking for no cucumbers in my salad, and yet here we are.', false),
            ('Pissin me pants.', false),
            ('A basketball that screams every time it gets boucned.', false),
            ('Elon Musk.', false),
            ('Rubbing my clit with a handgun.', false),
            ('Being hunted by giant eagles', false),
            ('The kind of porn with poop', false),
            ('Korean barbecue', false),
            ('A family of raccoons', false),
            ('The fact that time is moving backwards right now and nobodys noticing.', false),
            ('The pelican that will one day eat Scarlett Johanssons baby', false),
            ('Little Debbie and her mom, Full-Size Deborah.', false),
            ('The cutest fucking shoes Ive ever seen.', false),
            ('Shitting perfectly into a hot dog bun', false),
            ('A 12-food scepter of bone', false),
            ('Your mouth.', false),
            ('Making direct eye contact with a horses asshole', false),
            ('Lotion', false);

